---
- hosts: localhost

  become: yes
  become_method: sudo
  

  tasks:
  - name: Update and upgrade apt packages
    shell: "yum update -y"    # yum install code can be taken from ansible documentation

  - name: install JDK 1.8.0
    yum:
      name: java-1.8.0
      state: present

  - name: add tomcat group
    group:
      name: tomcat

  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no

  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: download & unarchive
    unarchive:
      src: http://apache.cs.utah.edu/tomcat/tomcat-9/v9.0.93/bin/apache-tomcat-9.0.93.tar.gz     # as per aug month need to check for version
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Change ownership
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

  - name: Copy Tomcat service from local to remote
    copy:
       src: tomcat.service
       dest: /etc/systemd/system/
       mode: 0755

  - name: reload the daemon            # if we want to restart we need do daemon reload
    shell: "systemctl daemon-reload" 

  - name: Start and enable Tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true
